DiabeticRetinopathyDetection/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
#from myapp import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('myapp.urls')),
    #url(r'^$', views.home_page, name='myapp-Page')
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'myapp'

urlpatterns = [

    url(r'^logout/$', views.Logout.as_view(), name='logout'),
    url(r'^$', views.HomePage.as_view(), name='Home'),
    url(r'^registration/$', views.Registration.as_view(), name='registration'),
    path('<str:user>/home/', views.UserHome.as_view(), name='UserHome'),
    path('<str:user>/profile/', views.UserProfile.as_view(), name='UserProfile'),

]

myapp/models.py
from datetime import datetime
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.conf import settings


# Create your models here.
class CustomUser(AbstractUser):
    address = models.CharField(max_length=25, null=True, blank=True)
    mobile_number = models.CharField(max_length=11, null=True, blank=True)
    last_checked = models.DateField(null=True, blank=True)
    health_condition = models.CharField(max_length=15, null=True, blank=True)


class Image(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    image = models.FileField(None)
    date = models.DateField(default=datetime.today())
    side = models.CharField(default='L', max_length=1)
    stage = models.CharField(default='1', max_length=10)

    def get_absolute_url(self):
        return reverse('', kwargs={'pk': self.pk})

    def __str__(self):
        return self.image.url

myapp/forms.py
from django import forms
from . import models
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CreateImage(forms.ModelForm):
    class Meta:
        model = models.Image
        fields = ['image']


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('username', 'password1', 'password2', 'first_name', 'last_name', 'mobile_number', 'address', 'email')


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email')

myapp/views.py
from django.shortcuts import render, redirect
from .models import Image as myImage
from .models import CustomUser
from .forms import CreateImage, CustomUserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.views.generic import View
from PIL import Image
from . import predict_app as pred
from django.http import Http404
from datetime import datetime


class HomePage(View):
    template_name = 'myapp/home page.html'

    def get(self, request):
        if str(request.user.username) == "":
            return render(request, self.template_name, {})
        else:
            return redirect('myapp:UserHome', request.user)

    def post(self, request):
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('myapp:UserHome', user)
        else:
            return render(request, self.template_name, {})


class Registration(CustomUserCreationForm, View):
    template_name = 'myapp/reg.html'
    form = CustomUserCreationForm()

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        self.form = CustomUserCreationForm(request.POST)
        self.form.first_name = request.POST.get('first_name')
        self.form.last_name = request.POST.get('last_name')
        self.form.password1 = request.POST.get('password1')
        self.form.password2 = request.POST.get('password2')
        if self.form.is_valid():
            user = self.form.save()
            login(request, user)
            return redirect('myapp:UserHome', user.username)
        else:
            return render(request, self.template_name)
        

class Logout(View):

    def get(self, request):
        logout(request)
        return redirect('myapp:Home')


class UserHome(LoginRequiredMixin, View):
    template_name = 'myapp/home page.html'

    def get(self, request, user):
        if str(request.user) != str(user):
            raise Http404()
        else:
            user = CustomUser.objects.get(username=request.user)
            context = {'user': user}
            return render(request, self.template_name, context)

    def post(self, request, user):
        form = CreateImage(request.POST, request.FILES)

        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            CUser = instance.user
            stream = request.FILES['image']
            img = Image.open(stream)
            predictions = pred.predict(img)
            result = 0
            max_probability = 0.0
            for i in range(0, 5):
                if max_probability < predictions[0][i]:
                    max_probability = predictions[0][i]
                    result = i + 1

            instance.stage = result
            if result > 1:
                CUser.health_condition = "Diseased"
            else:
                CUser.health_condition = "Healthy"

            instance.side = 'L'
            CUser.last_checked = datetime.today()
            instance.save()
            CUser.save()
            user = request.user
            imagee = myImage.objects.get(user=user, pk=instance.pk)
            return render(request, 'myapp/Stage.html', {'Stage': result, 'Image': imagee})


class UserProfile(LoginRequiredMixin, View):
    template_name = 'myapp/profile.html'

    def get(self, request, user):
        if str(request.user) != str(user):
            raise Http404()
        else:
            user = CustomUser.objects.get(username=user)
            UserImages = myImage.objects.filter(user=user)
            context = {'user': user, 'image_list': UserImages}
            return render(request, self.template_name, context)

myapp/templates/myapp/Base.html
<!DOCTYPE html>
{% load staticfiles %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> Diabetic Retinopathy </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

	<link rel="stylesheet" href="{% static 'login style.css' %}">
	<link rel="stylesheet" href="{% static 'uploadimg.css' %}">

<link rel="stylesheet" href="{% static 'home page.css' %}">

</head>

<body data-spy="scroll" data-target="#menu">

    <!---strat home section -->
    <div id ="home">



        <!---navigation-->
        <nav class="navbar navbar-dark navbar-expand-md fixed-top">
            <div class="container-fluid">
            {% if user.username != "" %}
                <a class="navbar-brand" href="{% url 'myapp:UserHome' user %}">
                    <img src="{% static 'img/logo.png'%}" >
                </a>
            {% else %}
                <a class="navbar-brand" href="{% url 'myapp:Home' %}">
                    <img src="{% static 'img/logo.png'%}" >
                </a>
            {% endif %}
                <button  class="navbar-toggler" type="button" data-toggle="collapse" data-target="#menu">
                    <span class="navbar-toggler-icon"></span>
                </button>
                    <div class="collapse navbar-collapse" id="menu">
                        <ul class="navbar-nav ml-auto">
                            {% if user.username == ""  %}
                            <li class="nav-link">
                                <a class="nav-link" href="{% url 'myapp:Home' %}">HOME</a>
                            </li>
                            {% endif %}
                            {% if user.username != ""  %}
                                <li class="nav-link">
                                <a class="nav-link" href="{% url 'myapp:UserHome' user %}">HOME</a>
                            </li>
                            {% endif %}
                             <li class="nav-link">
                                <a class="nav-link" href="#More">Know More</a>
                            </li>
                            <li class="nav-link">
                                <a class="nav-link" href="#about">ABOUT</a>
                            </li>

                            <li class="nav-link">
                                <a class="nav-link" href="#contact">CONTACT</a>
                            </li>
                            {% if user.username == ""  %}
                            <li class="nav-link">
                                        <a class="nav-link btn-outline-dark" data-toggle="modal" href="#modalLRForm">LOGIN</a>
                            </li>
                            <li class="nav-link">
                                        <a class="nav-link btn-outline-dark" href="{% url 'myapp:registration' %}">REGISTER</a>
                            </li>
                            {% endif %}
                            {% if user.username != "" %}
                                <li class="nav-link">
									<a class="nav-link" href="{% url 'myapp:UserProfile' user %}" >Welcome, {{ user.first_name }} {{ user.last_name }} </a>
								</li>
                                <form action="{% url 'myapp:logout' %}" method="post" role="form">
                                {% csrf_token %}
                                <li class="nav-link" >
                                    <a class="nav-link" href="{% url 'myapp:logout' %}" >Logout</a>
								</li>
                                </form>
                            {% endif %}
                        </ul>
                    </div>
                
            </div>
        </nav>
        </div>

    <form method="post" role="form" action="{% url 'myapp:Home' %}">
    {% csrf_token %}
	<!--Modal: Login / Register Form-->
	<div class="modal fade" id="modalLRForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	  <div class="modal-dialog cascading-modal" role="document">
	    <!--Content-->
	    <div class="modal-content">

	      <!--Modal cascading tabs-->
	      <div class="modal-c-tabs">

	        <!-- Tab panels -->
	        <div class="tab-content">
	          <!--Panel 7-->
	          <div class="tab-pane fade in show active" id="panel7" role="tabpanel">

	            <!--Body-->
             <div class="col-12 user-img">
                <img src="{% static 'img/login.jpg' %}">
                <h3>Login Info</h3>
            </div>


            <form class="col-12">
                <div class="form-group">
                    <input type="text" name="username" class="form-control" placeholder="Enter Username">
                </div>
                <div class="form-group">
                    <input type="password" name="password" class="form-control" placeholder="Enter Password">
                </div>
                <button type="submit" class="btn1" style="margin-left: 120px;"><i class="fas fa-sign-in-alt"></i>Login</button>
            </form>

            <div class="col-12 forgot">
                <a href="#">Forgot Password</a>
            </div>


        </div><!---- end of modal content-->

	          </div>
	          <!--/.Panel 7-->
	        </div>

	      </div>
	    </div>
	    <!--/.Content-->
	  </div>
	</div>
</div>
<!--Modal: Login / Register Form-->
    </form>
{% block body%}



{%endblock%}
</body>

myapp/templates/myapp/Stage.html
{% extends 'myapp/Base.html' %}

<head>
</head>
<body>
{% block body %}
<div class="container col-md-6 text-center" id="modalLRForm1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="col-auto main-section">
            <!--Content-->
            <div class="modal-content">

                                <!--Body-->


                                    <form class="container-fluid" id="MyForm1" action="" method="POST">
                                        <img src="{{ Image.image.url }}" style="width:350px !important; height:250px !important; margin-bottom: 20px; margin-top: 20px;">
                                    <h1 style="color:teal"><strong>Stage {{ Stage }}</strong></h1>
                                        <div class="row">
                                            <div class="col-12">
                                                {% if Stage == 1 %}
                                                <p style="color:greenyellow; font-size: 1.5rem;">You have healthy retina ^_^</p>
                                                    <div class="col-12 already">
                                                        <a target="_blank" href="https://www.diabetes.org.uk/guide-to-diabetes/complications/retinopathy/steps-you-can-take-to-avoid-retinopathy" style="color: royalblue">Tips to maintain healthy eyes</a>
                                                    </div>
                                                {% elif Stage == 2 %}
                                                     <p style="color:red; font-size: 1.5rem;">Unfortunately, You're diseased :(</p>
                                                <p style="color:white; font-size: 1.5rem;">This is the earliest stage of diabetic retinopathy, and it’s characterized by balloon-like swelling in the retina’s blood vessels. These are called microaneurysms, and these vessels can leak into the eye.</p>
                                                {% elif Stage == 3 %}
                                                    <p style="color:red; font-size: 1.5rem;">Unfortunately, You're diseased :(</p>
                                                <p style="color:white; font-size: 1.5rem;">During this stage, the blood vessels nourishing the retina swell and may even become blocked. This can contribute to diabetic macular edema (DME) which is a build-up of fluid in the macula region of the retina.</p>
                                                {% elif Stage == 4 %}
                                                    <p style="color:red; font-size: 1.5rem;">Unfortunately, You're diseased :(</p>
                                                <p style="color:white; font-size: 1.5rem;">At this stage, an increasing number of blood vessels nourishing the eye have become blocked. As a result, the retina is signaled to grow new blood vessels</p>
                                                {% elif Stage == 5 %}
                                                    <p style="color:red; font-size: 1.5rem;">Unfortunately, You're diseased :(</p>
                                                <p style="color:white; font-size: 1.5rem;">This is the final stage of diabetic retinopathy. New blood vessels proliferate, growing inside the retina and into the vitreous gel, which is the fluid that fills the eye. Because these blood vessels are delicate, they may begin to leak and bleed. As a result, scar tissue may form, causing retinal detachment, the pulling away of the retina from underlying tissue. Retinal detachment may cause spotty vision, flashes of lights, or severe vision loss.</p>
                                                {% endif %}
                                            </div>
                                        </div>
                                    </form>

</div>
            </div>
    </div>
</div>
</body>
{% endblock %}

myapp/templates/myapp/home page.html
{% extends 'myapp/Base.html'%}
{% load staticfiles %}
{% block body %}
<head>
    <link rel="stylesheet" href="{% static 'home page.css' %}">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
	<script src="{% static 'js/uploadimg.js' %}"></script>
</head>

<body data-spy="scroll" data-target="#menu">

    <!---strat home section -->

			<!--- start landing page-->
			<div class="landing">
				<div class="home-wrap">
					<div class="home-inner">
					</div>
				</div>
			</div>
			<!--- start landing page caption -->
			<div class="caption center-block text-center">
                <h3 style="font-family:Playfair Display, Georgia, Times New Roman, serif; font-size: 45px;"> Welcome to <strong>Diabetic Retinopathy Classification<br> System</strong></h3>
                {% if user.username != '' %}
				    <a class="btn btn-outline-light" data-toggle="modal" href="#modaluploadForm">Diagnose</a>
                {% endif %}
		</div><!---end home section-->


 <!--- img upload-->
 <div class="modal fade" id="modaluploadForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog cascading-modal" role="document">
				<!--Content-->
				<div class="modal-content">

						<!--Modal cascading tabs-->
						<div class="modal-c-tabs">



							<!-- Tab panels -->
							<div class="tab-content">
								<!--Panel 7-->
								<div class="tab-pane fade in show active" id="panel7" role="tabpanel">

									<!--Body-->
									<div class="col-12 user-img">
											<img src="{% static 'img/photo.png' %}">
										<h3>Upload Image</h3>
								</div>


								<form class="col-12" method="post" enctype="multipart/form-data">
                                    {% csrf_token %}
										<div class="imagePreview" >

										</div>

										<label class="btn1 col-12" type="submit" >Upload<input type="file" id="img-input" name="image" class="uploadFile img" value="Upload Photo" style="width: 0px;height: 0px;overflow:hidden;"></label>
                                    <button type="submit" class="btn1 col-12" >Classify</button>

								</form>

						</div><!---- end of modal content-->

								</div>
								<!--/.Panel 7-->
							</div>

						</div>
					</div>
					<!--/.Content-->

				</div><!-- col-2 -->

				</div><!-- row -->
		</div>
</div><!-- container -->
<!---end img upoad-->




<!--- start about section -->
    <div id="More">
			<div class="jumbotron text-center">
				<h1 class="headingg" ><strong>What is Diabetic Retinopathy ?</strong></h1>
				<div class="row">
					<div class="col-md-12 text-center">

						<p>
                            Diabetic retinopathy is an eye disease that people living with diabetes are more at risk of getting. If your blood sugar levels and blood pressure are consistently high, you can seriously damage your blood vessels.

And there are lots of important blood vessels in your eyes. These vessels help supply blood to the seeing part of the eye (called the retina). When these blood vessels are damaged, they can get blocked, leak or grow randomly. This means the retina can’t get the blood it needs and so can’t work properly. Which means you won’t be able to see properly.
						</p>
					</div>
				</div><!--- end of row-->
			</div><!--- end of jumbtron-->
		</div> <!---enf of the about section-->

    <div id="Stages">
			<div class="jumbotron text-center">
				<h1 class="headingg" ><strong>Stages of Diabetic Retinopathy ?</strong></h1>
				<div class="row">
					<div class="col-md-12 text-center" >
                        <h2 style="text-align: left; color: #00cc00">Stage 1 :</h2> <p style="text-align: left"><strong>Mild Nonproliferative</strong>, there will be balloon-like swelling in small areas of the blood vessels in the retina.</p>
                        <h2 style="text-align: left; color: darkorange">Stage 2 :</h2> <p style="text-align: left"> known as <strong> Moderate Nonproliferative Retinopathy</strong>, some of the blood vessels in the retina will become blocked.</p>
                        <h2 style="text-align: left; color: red">Stage 3 :</h2> <p style="text-align: left"><strong>Severe Nonproliferative Retinopathy</strong> brings with it more blocked blood vessels, which leads to areas of the retina no longer receiving adequate blood flow. Without proper blood flow, the retina can’t grow new blood vessels to replace the damaged ones.</p>
					    <h2 style="text-align: left; color: darkred;">Stage 4 :</h2> <p style="text-align: left">The fourth and final stage is known as <strong> Proliferative Retinopathy</strong>. This is the advanced stage of the disease. Additional new blood vessels will begin to grow in the retina, but they will be fragile and abnormal. Because of this, they can leak blood which will lead to vision loss and possibly blindness.</p>
                    </div>
				</div><!--- end of row-->
			</div><!--- end of jumbtron-->
		</div> <!---enf of the about section-->

		<div id="about">
			<div class="jumbotron text-center">
				<h1 class="headingg" ><strong>ABOUT</strong></h1>
				<div class="row">
					<div class="col-md-12 text-center">
						<h3><strong>A Group of Computer Science  Bioinformatics Section Ain Shams University Students</strong></h3>
						<p>Developed a diagnostic System to automate DR screening. Referral of eyes with DR to an ophthalmologist for further evaluation and treatment would aid in reducing the rate of vision loss, enabling timely and accurate diagnoses.
						</p>
					</div>
				</div><!--- end of row-->
			</div><!--- end of jumbtron-->
		</div> <!---enf of the about section-->

		<!---start of contact section-->
		<div id="contact">
			<div class="container-fluid footer">
				<div class="row">
					<div class="col-md-3"></div>
					<div class="col-md-6 text-center">
						<img src="{% static 'img/logo.png' %}">
						<p><strong>Contact Information</strong></p>
						<p>graduationprojectdr@gmail.com</p>
						<a href="https://www.facebook.com"><img src="{% static 'img/facebook.png' %}"></a>
						<a href="https://www.twitter.com"><img src="{% static 'img/twitter.png' %}"></a>
						<a href="https://www.instagram.com"><img src="{% static 'img/instagram.png' %}"></a>
					</div>
					<div>

					</div>
				</div><!---end of row-->
			</div><!---end of container fluid footer-->
		</div><!---end of contact section-->





	</body>
{% endblock %}

myapp/templates/myapp/profile.html
{% extends 'myapp/Base.html' %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
{% block body %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="style.css">
    <title>Profile</title>
    <link rel="stylesheet" href="{% static 'profilestyle.css' %}">
</head>
<body>
    <div style="margin-top: 100px; margin-left: 30px" class="container"><br>
        <div class="row">
            <div class="col-sm-1"></div>
            <div class="col-sm-9">
                <nav>
                    <div class="nav nav-tabs" id="nav-tab" role="tablist" >
                      <a class="nav-item nav-link active" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false" style="color: #7a7c11; font-size: 30px;"><strong>Profile</strong></a>
                        <a class="nav-item nav-link" id="nav-contact-tab" data-toggle="tab" href="#nav-contact" role="tab" aria-controls="nav-contact" aria-selected="false" style="color: #7a7c11; font-size: 30px;"><strong>Eye Scan History</strong></a>
                    </div>
                  </nav>
                  <div class="tab-content" id="nav-tabContent">
                    <div class="tab-pane fade show active" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
                        <div class="col-sm-2"></div>
                        <div class="col-sm-8 col-xs-10">
                                <div class="row">
                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" style="border-radius: 40px;">
                                        <div class="well profile col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center">
                                                <br>
                                                <h3 style="text-align:center; color: white; "><strong id="user-name">{{user.username}}</strong></h3>
                                                <p style="text-align:left;font-size: medium;color: white;" id="user-frid">First Name : {{user.first_name}} </p>
                                                <p style="text-align:left;font-size: medium;color: white;" id="user-frid">Last Name : {{user.last_name}} </p>
                                                <p style="text-align:left;font-size: medium;color: white;" id="user-frid">Address : {{user.address}} </p>
                                                <p style="text-align:left;font-size: medium;overflow-wrap: break-word;color: white;" id="user-email">Email : {{user.email}}</p>
                                                <p style="text-align:left;font-size: medium;overflow-wrap: break-word;color: white;" id="user-email">Mobile : {{user.mobile_number}}</p>

                                                {% if user.health_condition == 'Healthy' %}
                                                    <p style="text-align:left;font-size: medium; color: white;">Health status: <span class="badge badge-success">{{ user.health_condition}}</span>
                                                {% elif user.health_condition == 'Diseased' %}
                                                    <p style="text-align:left;font-size: medium; color: white;">Health status: <span class="badge badge-danger">{{ user.health_condition}}</span>
                                                {% endif %}
                                                <hr>


                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">
                         <ul>
                        {% for image in image_list %}
                            <div class="gallery">
                                <a target="_blank">
                                  <img src={{ image.image.url }} width="600" height="400">
                                </a>
                                <div class="desc" style="color: white;">Result: {{image.stage }}<br>
                                    <small><strong>{{ image.date }}</strong></small>
                                </div>
                            </div>
                        {% endfor %}
                         </ul>
                    </div>
                  </div>
            </div>
        </div>
    </div>
</body>
</html>
{% endblock %}